export const ALL_ALBUM_REQUEST = "ALL_ALBUM_REQUEST";
export const ALL_ALBUM_SUCCESS = "ALL_ALBUM_SUCCESS";
export const ALL_ALBUM_FAIL = "ALL_ALBUM_FAIL";

export const ALBUM_DETAIL_REQUEST = "ALBUM_DETAIL_REQUEST";
export const ALBUM_DETAIL_SUCCESS = "ALBUM_DETAIL_SUCCESS";
export const ALBUM_DETAIL_FAIL = "ALBUM_DETAIL_FAIL";

export const SONG_DELETE_SUCCESS = "SONG_DELETE_SUCCESS";
export const SONG_DELETE_FAIL = "SONG_DELETE_FAIL";
export const SONG_DELETE_RESET = "SONG_DELETE_RESET";

export const CREATE_ALBUM_REQUEST = "CREATE_ALBUM_REQUEST";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAIL = "CREATE_ALBUM_FAIL";
export const CREATE_ALBUM_RESET = "CREATE_ALBUM_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
