export const ALL_ALBUM_REQUEST = "ALL_ALBUM_REQUEST";
export const ALL_ALBUM_SUCCESS = "ALL_ALBUM_SUCCESS";
export const ALL_ALBUM_FAIL = "ALL_ALBUM_FAIL";

export const ALBUM_DETAIL_REQUEST = "ALBUM_DETAIL_REQUEST";
export const ALBUM_DETAIL_SUCCESS = "ALBUM_DETAIL_SUCCESS";
export const ALBUM_DETAIL_FAIL = "ALBUM_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
