export const SONG_DETAIL_REQUEST = "SONG_DETAIL_REQUEST";
export const SONG_DETAIL_SUCCESS = "SONG_DETAIL_SUCCESS";
export const SONG_DETAIL_FAIL = "SONG_DETAIL_FAIL";

export const SONG_AUDIO_REQUEST = "SONG_AUDIO_REQUEST";
export const SONG_AUDIO_SUCCESS = "SONG_AUDIO_SUCCESS";
export const SONG_AUDIO_FAIL = "SONG_AUDIO_FAIL";

export const CREATE_SONG_REQUEST = "CREATE_SONG_REQUEST";
export const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS";
export const CREATE_SONG_FAIL = "CREATE_SONG_FAIL";
export const CREATE_SONG_RESET = "CREATE_SONG_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
